### ISSUE TITLE
Lack of input validation RLN.register may lead to user loss of funds

### ISSUE THREAD

**Issue by aviggiano** [Rate-Limiting-Nullifier/rln-contract#3]
# Description

`RLN.register` calculates the `messageLimit` by performing an integer division of the `amount` over the `MINIMAL_DEPOSIT`. 

https://github.com/Rate-Limiting-Nullifier/rln-contracts/blob/main/src/RLN.sol#L120-L121

```solidity
        token.safeTransferFrom(msg.sender, address(this), amount);
        uint256 messageLimit = amount / MINIMAL_DEPOSIT;
```

If `amount` is greater than `MINIMAL_DEPOSIT` but is not a multiple of it, the user will have transferred more tokens than necessary.

# Recommendation

Validate that `amount` is a multiple of `MINIMAL_DEPOSIT`

```solidity
        require(amount % MINIMAL_DEPOSIT == 0, "RLN, register: user provided higher amount than necessary");
```

**Comment by curryrasul** [comment]
Thanks, actually we thought about it. I wouldn't say that this is "security bug" though. If a user send not correct amount - that's his fault:) But good catch, maybe worth to add it. 
Could you do a PR ?

**Comment by aviggiano** [comment]
> Thanks, actually we thought about it. I wouldn't say that this is "security bug" though. If a user send not correct amount - that's his fault:) But good catch, maybe worth to add it. Could you do a PR ?

Sure! 
Submitted.

I agree. It is a user error, so not a big deal. The thing is that the additional amount would be trapped in the contract forever, it wouldn't be redistributed to other participants or sent to the fee receiver, so the additional check is a minor improvement I guess.

**Comment by whoismatthewmc1** [comment]
I also noticed this one.
Since it is clearly a user error, I think the other (but less desirable IMO) alternative is simply documenting that any amount other than a multiple of `MINIMAL_DEPOSIT` will be lost.
