### ISSUE TITLE
Minor gas optimization suggestions

### ISSUE THREAD

**Issue by lwltea** [Rate-Limiting-Nullifier/rln-contract#7]
Some minor gas optimization suggestions:
1. Replace `require` statements with custom errors. They are more gas efficient generally. See: https://blog.soliditylang.org/2021/04/21/custom-errors/
2. Put `identityCommitmentIndex += 1;` in a `unchecked` block as its a `uint256` being incremented by 1. Range checks are unnecessary here.

**Comment by whoismatthewmc1** [comment]
I'll add on to this issue rather than creating an additional one:

3. Remove unnecessary initialization of `identityCommitmentIndex = 0` since default value will be 0. (https://github.com/Rate-Limiting-Nullifier/rln-contracts/blob/main/src/RLN.sol#L52)

**Comment by curryrasul** [comment]
Hey @lwltea @whoismatthewmc1 , We tried custom errors - that doesn't save that much gas but `require`s are cleaner, imo. 
About Unchecked increment and unnecessary initialization - I'll do that, thanks a lot!
